version: "3.2"

services:
  db:
    container_name: digitopia-postgresql
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - new-network
    restart: always
    environment:
      POSTGRES_DB: digitopia
      POSTGRES_USER: digitopia
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: digitopia-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: goodbook@realworld.com
      PGADMIN_DEFAULT_PASSWORD: realworld
    ports:
      - "9090:80"
    networks:
      - new-network
    restart: always

networks:
  new-network:
    driver: bridge